### ISSUE TITLE
12 , 3，6 , 9的小时刻度的位置问题

### ISSUE THREAD

**Issue by benjious** [MonkeyMushroom/MiClockView#1]
您好，我想问一下，3和9两个小时刻度是如何定位的？？
为什么这里
`（getWidth() - mPaddingRight - mTextRect.height() / 2 - textSmallWidth / 2,
                getHeight() / 2 + mTextRect.height() / 2）`的xy是这样的，有点不明白。

**Comment by benjious** [comment]
哦，知道了是基线（baseline）问题

**Comment by MonkeyMushroom** [comment]
就是12和3、6、9的宽度不一样，高度一样，可以看我博客里面的示意图哦

**Comment by benjious** [comment]
恩恩，我有去看，有点地方不懂的就是
`mCanvas.drawText("3", getWidth() - mPaddingRight - mTextRect.height() / 2 - textSmallWidth / 2,
                getHeight() / 2 + mTextRect.height() / 2, mTextPaint);`
绘画“3”的时候，drawText( x , y )中，x不是代表左下角的坐标吗，那么x不应该是 ;
`getWidth() - mPaddingRight - textSmallWidth `
不是很明白，求指点

**Comment by MonkeyMushroom** [comment]
就是如果把12按圆的弧线顺时针旋转到3的位置，12的高是3的大宽，3的宽是小宽，你只减去小宽，3的中心不在圆上的，我可能讲不明白。。
