### ISSUE TITLE
 mCamera.translate(x, y, z) 方法改变 z 的值 没有效果的原因找到了

### ISSUE THREAD

**Issue by renjinlong** [MonkeyMushroom/MiClockView#2]
查阅 Rotate3dAnimation的景深效果
@Override  
    protected void applyTransformation(float interpolatedTime, Transformation t) {  
        super.applyTransformation(interpolatedTime, t);  
        float fromDegree = startDegree;  
        float degree = fromDegree + (endDegree - startDegree) * interpolatedTime;  
  
        final Matrix matrix = t.getMatrix();  
  
        mCamera.save();  
        if (mReverse) {  
            mCamera.translate(0, 0, deepZ * interpolatedTime);  
        } else {  
            mCamera.translate(0, 0, deepZ * (1 - interpolatedTime));  
        }  
        if (direction == DIRECTION.Y) {  
            mCamera.rotateY(degree);  
        } else {  
            mCamera.rotateX(degree);  
        }  
        mCamera.getMatrix(matrix);  
        mCamera.restore();  
  
        matrix.preTranslate(-centerX, -centerY);  
        matrix.postTranslate(centerX, centerY);  
    }

需要先translate    然后rotate就会出现景深效果了

**Comment by MonkeyMushroom** [comment]
感谢！
